In [2]:
import pandas as pd

In [4]:
mov = pd.read_csv('../data/train_imdb.csv', index_col=0)

In [6]:
mov.head()

,movie,genre,labelled_genre,first_genre,summary
0,Flaming Brothers,"Action,Crime,Romance",Action,Action,tale two brother one left triad gone legit dec...
1,Uchronia,"Drama,Fantasy",Fantasy,Drama,earth enabl alien layla majnun becom human fin...
2,Button for Dreams,Animation,Animation,Animation,like everi night littl oggi lie cot grandfath ...
3,Girlfriends,"Comedy,Drama",Comedy,Comedy,photograph girlfriend roommat stuck small chan...
4,Hangman's Noose,"Mystery,Sci-Fi,Thriller",Sci-Fi,Mystery,stori man taken time foreign scienc becom hybr...

In [7]:
import math
cutoff = math.floor(len(mov)*0.8)

In [8]:
print(cutoff)

16675

In [9]:
mov[:cutoff]

,movie,genre,labelled_genre,first_genre,summary
0,Flaming Brothers,"Action,Crime,Romance",Action,Action,tale two brother one left triad gone legit dec...
1,Uchronia,"Drama,Fantasy",Fantasy,Drama,earth enabl alien layla majnun becom human fin...
2,Button for Dreams,Animation,Animation,Animation,like everi night littl oggi lie cot grandfath ...
3,Girlfriends,"Comedy,Drama",Comedy,Comedy,photograph girlfriend roommat stuck small chan...
4,Hangman's Noose,"Mystery,Sci-Fi,Thriller",Sci-Fi,Mystery,stori man taken time foreign scienc becom hybr...
...,...,...,...,...,...
16670,Most Dangerous Man Alive,Sci-Fi,Sci-Fi,Sci-Fi,wander nuclear test area desert escap mobster ...
16671,Crawlers,Horror,Horror,Horror,year zombi pandem biblic proport decim unit st...
16672,Red Girl,"Fantasy,Mystery,Sci-Fi",Fantasy,Fantasy,inform found
16673,The Mandalorian Legacy,Sci-Fi,Sci-Fi,Sci-Fi,boba fett undergo physic emot hardship mold ha...
16674,Echo Dr.,"Action,Drama,Sci-Fi",Sci-Fi,Action,home secur system malfunct famili struggl surv...

In [10]:
mov[cutoff:]

,movie,genre,labelled_genre,first_genre,summary
16675,The Shimian,Horror,Horror,Horror,famili take camp trip forest celebr birthday f...
16676,The Wedding Weekend,"Comedy,Drama,Music",Comedy,Comedy,group guy sang togeth colleg cappella group re...
16677,Ali Baba and the Seven Dwarfs,"Action,Comedy,Drama",Action,Action,ali ilber two partner senay c ccaciy sell gard...
16678,Dinosaurs at Dusk,"Documentary,Short,Adventure",Adventure,Documentary,dinosaur dusk fantasi adventur explor origin f...
16679,Horseplay: Jungle-Mania,"Documentary,Animation,Short",Animation,Documentary,scout hors hop trusti plane axel set incred le...
...,...,...,...,...,...
20839,Sentinel 2099 SE,Sci-Fi,Sci-Fi,Sci-Fi,post apocalypt world st centuri unifi commonwe...
20840,Society of Explorers and Adventurers,Adventure,Adventure,Adventure,plot wrap
20841,Origins IV: Revelations,"Action,Adventure,Drama",Sci-Fi,Action,star war fan film set year episod year sinc ev...
20842,The Death Kiss,"Comedy,Crime,Drama",Comedy,Comedy,murder film shoot spark search killer
20843,Oddballs,Comedy,Comedy,Comedy,canadian sex comedi save summer camp becom sho...

In [11]:
test = pd.read_csv('../data/test_imdb.csv', index_col=1)

In [12]:
test.groupby('labelled_genre').size()

labelled_genre
Action       816
Adventure    813
Animation    636
Comedy       756
Fantasy      667
Horror       828
Sci-Fi       695
dtype: int64